name: DeployToGitHubPages
env:
  CLIENT_APP_ROOT: src/QuickGridDemos
  PUBLISH_DIR: src/QuickGridDemos/bin/Release/net7.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.100-preview.5.22307.18'
        include-prerelease: true

    - name: Publish app
      run: cd ${{ env.CLIENT_APP_ROOT }} && dotnet publish -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /QuickGridDemos/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
